apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loadgenerator.fullname" . }}
  labels:
    {{- include "loadgenerator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "loadgenerator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "loadgenerator.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.waitForServices.enabled }}
      initContainers:
        - name: wait-for-services
          image: {{ .Values.initContainer.image }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "Waiting for services to be ready..."
              timeout={{ .Values.waitForServices.timeout }}
              interval={{ .Values.waitForServices.checkInterval }}
              start_time=$(date +%s)
              
              # Single check function
              check_service_once() {
                local name=$1
                local port=$2
                local path=$3
                
                if [ -n "$path" ]; then
                  # HTTP health check
                  http_code=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "http://$name:$port$path" 2>/dev/null)
                  if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 500 ]; then
                    return 0
                  fi
                else
                  # TCP port check
                  if nc -z $name $port 2>/dev/null; then
                    return 0
                  fi
                fi
                return 1
              }
              
              # Wait for specific service
              wait_for_service() {
                local name=$1
                local port=$2
                local path=$3
                
                echo "Waiting for $name:$port$path"
                
                while true; do
                  current_time=$(date +%s)
                  elapsed=$((current_time - start_time))
                  if [ $elapsed -gt $timeout ]; then
                    echo "Timeout waiting for $name"
                    exit 1
                  fi
                  
                  if check_service_once "$name" "$port" "$path"; then
                    echo "$name is ready"
                    return 0
                  fi
                  
                  echo "$name not ready, waiting $interval seconds..."
                  sleep $interval
                done
              }
              
              # Create array of services to check
              services=(
              {{- range .Values.waitForServices.services }}
                "{{ .name }}:{{ .port }}:{{ .path | default "" }}"
              {{- end }}
              )
              
              # First round: parallel check all services
              echo "Performing initial parallel check of all services..."
              ready_services=()
              pending_services=()
              
              for service in "${services[@]}"; do
                IFS=':' read -r name port path <<< "$service"
                if check_service_once "$name" "$port" "$path"; then
                  echo "$name is ready"
                  ready_services+=("$service")
                else
                  echo "$name is not ready"
                  pending_services+=("$service")
                fi
              done
              
              # If all services are ready, exit
              if [ ${#pending_services[@]} -eq 0 ]; then
                echo "All services are ready!"
                exit 0
              fi
              
              echo "Ready services: ${#ready_services[@]}"
              echo "Pending services: ${#pending_services[@]}"
              
              # Second round: wait for pending services
              for service in "${pending_services[@]}"; do
                IFS=':' read -r name port path <<< "$service"
                wait_for_service "$name" "$port" "$path"
              done
              
              echo "All services are ready!"
          resources:
            {{- toYaml .Values.initContainer.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BASE_URL
              value: "{{ .Values.baseURL }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.opentelemetry.endpoint }}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: "{{ include "loadgenerator.fullname" . }}"
            - name: SERVICE_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=loadgenerator-service,service.namespace={{ .Release.Namespace }},pod.name=$(POD_NAME)"
          args:
            {{- if .Values.config.debug }}
            - "--debug"
            {{- end }}
            - "--threads={{ .Values.config.threads }}"
            - "--sleep={{ .Values.config.sleep }}"
            {{- if .Values.config.chain }}
            - "--chain={{ .Values.config.chain }}"
            - "--count={{ .Values.config.count }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
