# Default values for loadgenerator

replicaCount: 1

image:
  repository: 10.10.10.240/library/loadgenerator
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podAnnotations: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

baseURL: "http://ts-ui-dashboard:8080"

opentelemetry:
  endpoint: "opentelemetry-collector-deployment.monitoring:4317"


config:
  debug: false
  threads: 1
  sleep: 1000
  # chain: ""
  # count: 1


waitForServices:
  enabled: true
  timeout: 600  
  checkInterval: 1
  services:
    - name: ts-auth-service
      port: 8080
      path: "/api/v1/auth"
    - name: ts-user-service
      port: 8080
      path: "/api/v1/userservice/users"
    - name: ts-order-service
      port: 8080
      path: "/api/v1/orderservice"
    - name: ts-travel-service
      port: 8080
      path: "/api/v1/travelservice"
    - name: ts-travel2-service
      port: 8080
      path: "/api/v1/travel2service"
    - name: ts-preserve-service
      port: 8080
      path: "/api/v1/preserveservice"
    - name: ts-basic-service
      port: 8080
      path: "/api/v1/basicservice"
    - name: ts-station-service
      port: 8080
      path: "/api/v1/stationservice"
    - name: ts-train-service
      port: 8080
      path: "/api/v1/trainservice"
    - name: ts-route-service
      port: 8080
      path: "/api/v1/routeservice"
    - name: ts-price-service
      port: 8080
      path: "/api/v1/priceservice"
    - name: ts-seat-service
      port: 8080
      path: "/api/v1/seatservice"
    - name: ts-security-service
      port: 8080
      path: "/api/v1/securityservice"
    - name: ts-payment-service
      port: 8080
      path: "/api/v1/paymentservice"
    - name: ts-admin-basic-info-service
      port: 8080
      path: "/api/v1/adminbasicservice"
    - name: ts-admin-order-service
      port: 8080
      path: "/api/v1/adminorderservice"
    - name: ts-admin-route-service
      port: 8080
      path: "/api/v1/adminrouteservice"
    - name: ts-admin-travel-service
      port: 8080
      path: "/api/v1/admintravelservice"
    - name: ts-admin-user-service
      port: 8080
      path: "/api/v1/adminuserservice/users"
    - name: ts-assurance-service
      port: 8080
      path: "/api/v1/assuranceservice"
    - name: ts-avatar-service
      port: 8080
      path: "/api/v1/avatar"
    - name: ts-cancel-service
      port: 8080
      path: "/api/v1/cancelservice"
    - name: ts-config-service
      port: 8080
      path: "/api/v1/configservice"
    - name: ts-consign-price-service
      port: 8080
      path: "/api/v1/consignpriceservice"
    - name: ts-consign-service
      port: 8080
      path: "/api/v1/consignservice"
    - name: ts-contacts-service
      port: 8080
      path: "/api/v1/contactservice"
    - name: ts-execute-service
      port: 8080
      path: "/api/v1/executeservice"
    - name: ts-food-service
      port: 8080
      path: "/api/v1/foodservice"
    - name: ts-inside-payment-service
      port: 8080
      path: "/api/v1/inside_pay_service"
    - name: ts-notification-service
      port: 8080
      path: "/api/v1/notifyservice"
    - name: ts-order-other-service
      port: 8080
      path: "/api/v1/orderOtherService"
    - name: ts-preserve-other-service
      port: 8080
      path: "/api/v1/preserveotherservice"
    - name: ts-rebook-service
      port: 8080
      path: "/api/v1/rebookservice"
    - name: ts-route-plan-service
      port: 8080
      path: "/api/v1/routeplanservice"
    - name: ts-station-food-service
      port: 8080
      path: "/api/v1/stationfoodservice"
    - name: ts-train-food-service
      port: 8080
      path: "/api/v1/trainfoodservice"
    - name: ts-travel-plan-service
      port: 8080
      path: "/api/v1/travelplanservice"
    - name: ts-verification-code-service
      port: 8080
      path: "/api/v1/verifycode"
    - name: ts-wait-order-service
      port: 8080
      path: "/api/v1/waitorderservice"
    - name: ts-food-delivery-service
      port: 8080
      path: "/api/v1/fooddeliveryservice"
    - name: mysql
      port: 3306
    - name: rabbitmq
      port: 5672

initContainer:
  image: 10.10.10.240/library/netshoot:v0.14
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

initContainer:
  image: nicolaka/netshoot:latest
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
