# Default values for loadgenerator

replicaCount: 1

image:
  repository: 10.10.10.240/library/loadgenerator
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podAnnotations: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Application specific configuration
baseURL: "http://ts-ui-dashboard:8080"

# OpenTelemetry configuration
opentelemetry:
  endpoint: "opentelemetry-collector-deployment.monitoring:4317"

# Command line arguments from main.go
config:
  debug: false
  threads: 5
  sleep: 500
  # chain: ""
  # count: 1


waitForServices:
  enabled: false
  timeout: 600  
  checkInterval: 10 
  services:
    - name: ts-ui-dashboard
      port: 8080
      path: "/"

initContainer:
  image: nicolaka/netshoot:latest
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
